language: go

install: go get -v github.com/gohugoio/hugo

script:
    - hugo
    
deploy:
    - cd ./public
    - git config user.name "holten"
    - git config user.email "holten.ko@foxmail.com"
    - git init
    - git add .
    - git commit -m "Travis-CI 自动部署"
    # Coding Pages
    #- git push --force "https://<username>:${CO_TOKEN}@${CO_REF}" master:master # username替换为你的coding用户名
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - source

env:
    global:
        # Coding Pages
        #- CO_REF: # 这里填入你的coding pages仓库地址 例如：git.coding.net/username/hugo.git    
        - GH_REF: github.com/holtenko/blog
