name: hexo deploy

on:
  push:
    branches:
    - source

jobs:
  build: # 一项叫做build的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@master # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 10.x # 配置Node环境
      uses: actions/setup-node@master # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "10.x"
    
    - name: Setup Hexo env
      run: |
        # install dependencies
        npm i -g hexo-cli # 安装hexo
        npm i
  
    - name: Generate
      run: |
        # generate
        hexo generate # 执行部署程序
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
